"""Added role to User

Revision ID: 7d96903ff888
Revises: 
Create Date: 2023-09-02 12:17:09.155055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d96903ff888'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_role', 'role', ['role_id'], ['id'])
        # I noticed you're trying to drop a column named 'role', but it's not clear why. 
        # If this column doesn't exist in the 'user' table or if you're not sure about it,
        # you might want to comment out or remove the next line.
        # batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_user_role', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
